# Generated by Django 5.0.2 on 2025-02-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
