# Generated by Django 5.0.2 on 2025-02-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_image_comment_likes_alter_user_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
