# Generated by Django 5.0.2 on 2025-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_preview_image_post_preview_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
