# Generated by Django 5.0.2 on 2025-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_preview_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='preview_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='preview_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='preview_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
